### ISSUE TITLE
error: trying to load .blend file, but no blender installation was found. blender_paths:

### ISSUE THREAD

**Issue by Shidouuu** [pokepetter/pyweek_30_castaway#3]
```bash
PS C:\Users\[Username]\Documents\UrsinaProjects\pyweek_30_castaway> python main.py
info: Using primary monitor: Monitor(x=0, y=0, width=1920, height=1080, width_mm=344, height_mm=194, name='\\\\.\\DISPLAY1', is_primary=True)
:prc(warning): Invalid integer value for ConfigVariable win-size: 864.0
:prc(warning): Invalid integer value for ConfigVariable win-size: 1536.0
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
set window position: Vec2(192, 108)
:prc(warning): changing default value for ConfigVariable paste-emit-keystrokes from '1' to '0'.
info: loaded settings from settings.py successfully
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
package_folder: C:\Users\[Username]\AppData\Roaming\Python\Python312\site-packages\ursina
asset_folder: .
info: reload:
info: loading blender scene: castaway_island.blend --> scenes\castaway_island.ursina_blender_scene
Traceback (most recent call last):
  File "C:\Users\[Username]\Documents\UrsinaProjects\pyweek_30_castaway\main.py", line 12, in <module>
    level = load_blender_scene(path = application.asset_folder,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Username]\AppData\Roaming\Python\Python312\site-packages\ursina\mesh_importer.py", line 157, in load_blender_scene
    get_blender(blend_file),
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[Username]\AppData\Roaming\Python\Python312\site-packages\ursina\mesh_importer.py", line 191, in get_blender
    raise Exception('error: trying to load .blend file, but no blender installation was found. blender_paths:', application.blender_paths)
Exception: ('error: trying to load .blend file, but no blender installation was found. blender_paths:', {})
```
I don't have Blender on my system, but I wouldn't think I would need it to run this game. Does Castaway require Blender to run?

**Comment by Shidouuu** [comment]
> Does Castaway require Blender to run?

Apparently so, according to the [Urisna dependencies](https://github.com/pokepetter/ursina#Dependencies) 🙃
