### ISSUE TITLE
error: trying to load .blend file

### ISSUE THREAD

**Issue by alderven** [pokepetter/pyweek_30_castaway#5]
```
C:\Users\User\Downloads\pyweek_30_castaway-master>main.py
:prc(warning): Invalid integer value for ConfigVariable win-size: 864.0
:prc(warning): Invalid integer value for ConfigVariable win-size: 1536.0
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
set window position: Vec2(192, 108)
:prc(warning): changing default value for ConfigVariable paste-emit-keystrokes from '1' to '0'.
info: loaded settings from settings.py successfully
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
package_folder: C:\Program Files\Python312\Lib\site-packages\ursina
asset_folder: C:\Users\User\Downloads\pyweek_30_castaway-master
info: reload:
info: loading blender scene: C:\Users\User\Downloads\pyweek_30_castaway-master\castaway_island.blend --> C:\Users\User\Downloads\pyweek_30_castaway-master\scenes\castaway_island.ursina_blender_scene
Traceback (most recent call last):
  File "C:\Users\User\Downloads\pyweek_30_castaway-master\main.py", line 12, in <module>
    level = load_blender_scene(path = application.asset_folder,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ursina\mesh_importer.py", line 148, in load_blender_scene
    get_blender(blend_file),
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\ursina\mesh_importer.py", line 181, in get_blender
    raise Exception('error: trying to load .blend file, but no blender installation was found. blender_paths:', application.blender_paths)
Exception: ('error: trying to load .blend file, but no blender installation was found. blender_paths:', {})
```

**Comment by pokepetter** [comment]
The project didn't work with newer versions of blender/ursina, but that's been fixed now.
